### ISSUE TITLE
Alias, resizable components, etc...

### ISSUE THREAD

**Issue by jmgk77** [rogerdahl/striprouter#5]
Hi, me again...

Other useful commands would be a alias (=) in .circuit files. Let's say:
```
# Packages
T 0,0 0,1 0,2
R 0,0 0,1

# Components
T1 T 10,10
R1 R 15, 15

# Alias
BCC548 = T1
T1_BASE = T1.2

# Connection
T1.3 R1.2
BCC548.1 R1.2
T1_BASE R1.1
```
A dictionary build on CircuitFileParser::parseLine() and a CheckAlias on CircuitFileParser::parseConnection() line 223 should do, i believe

Resizable packages would also be nice (for things like resistors and diodes). Let's say:
```
# Packages
D 0,0 0,1 *3
```
Would allow D to be 0,0 0,1, and ... 0,2, ...0,3 or ... 0,4

Finally, an option to break the tracks in the holes would be welcome too.

I hope i'm not overstepping, and you reply "fork and do it yourself" :-)

**Comment by rogerdahl** [comment]
Alias: I don't think I'd use them. Having multiple names for the same thing seems like it would be just confusing. It would be easier to write but harder to read, and readability is more important. Of course, supporting them doesn't mean that people would have to use them and, as you mentioned, it's a simple change.

Resizable package: Yes, it's one I have wanted to implement. For things like resistors and diodes, it would allow the autorouter to automatically include the variations in the search, which could be really helpful.

Option to break the track in the holes: Also one I've wanted to implement. Having to cut between the holes is doable as long as the cuts are done before soldering, but still cumbersome.

I won't bore you with the details, but adding the ability to make the path finder (A*) reserve holes for the cuts is finicky, and I started a new version to address that, but didn't get it to a releasable state. I have been planning for a while to do a new implementation of this project in the Rust programming language, which I'm now getting into. That version would contain a path finder that would be easier to extend, and could handle things like reserving holes for cuts. Since that's the case, I'm not really motivated to be putting significant work into this version of the router. Sorry... But PRs are of course welcome :)

**Comment by jmgk77** [comment]
It's fair. :-)

I'll try to do a PR for the alias command, to familiarize myself with your code. If all goes well, I try harder PRs

**Comment by jmgk77** [comment]
Hi,

Finally did the PR for alias command.

**Comment by rogerdahl** [comment]
Thanks again!
